name: "[Cron] Merge Upstream"

on:
  schedule:
    - cron: "0 2 * * *"
  # Allow manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/swiftlang/swift-evolution.git
          git remote -v

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main

  update-masking-quiz:
    uses: ./.github/workflows/update-masking-quiz.yaml
    needs: merge-upstream
    secrets:
      MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
      MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
      R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
