name: "Update Masking Quiz"

on:
  workflow_dispatch: # Allow manual trigger
  workflow_run:
    workflows: "[Cron] Merge Upstream"
    types:
      - completed
  workflow_call:
    secrets:
      MICROCMS_API_KEY:
        required: true
      MICROCMS_SERVICE_DOMAIN:
        required: true
      R2_ENDPOINT_URL:
        required: true
      R2_ACCESS_KEY_ID:
        required: true
      R2_SECRET_ACCESS_KEY:
        required: true
      R2_BUCKET_NAME:
        required: true

defaults:
  run:
    shell: bash

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mask-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests \
            python-frontmatter \
            markdown \
            pygments \
            spacy \
            matplotlib \
            numpy \
            pandas \
            boto3 \
            beautifulsoup4 \
            python-dotenv \
            scikit-learn \
            tqdm
          python -m spacy download en_core_web_md

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Process and upload proposals
        run: |
          python .github/scripts/mask_and_upload.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: word_freq_hist
          path: artifacts/
